module.exports = {
  "Mobiles": require('../../data-scripts/resources/categories-brands/mobiles__brands.js'),
  "TV & Home Theater": require('../../data-scripts/resources/categories-brands/tv-&-home-theater__brands.json'),
  "Washing Machines": require('../../data-scripts/resources/categories-brands/washing-machines__brands.json'),
  "Laptops": require('../../data-scripts/resources/categories-brands/laptops__brands.json'),
  "Refrigerators": require('../../data-scripts/resources/categories-brands/refrigerators__brands.json'),
  "Cooker": require('../../data-scripts/resources/categories-brands/cooker__brands.json'),
  // revisit
  "Air Conditioners": require('../../data-scripts/resources/categories-brands/hair-dryers__brands.json'),
  "Shaving / Trimming": require('../../data-scripts/resources/categories-brands/shaving---trimming__brands.json'),
  "Hair Dryers": require('../../data-scripts/resources/categories-brands/hair-dryers__brands.json'),
  "Hair Stylers": require('../../data-scripts/resources/categories-brands/hair-stylers__brands.json'),
  "Dishwashers": require('../../data-scripts/resources/categories-brands/dishwashers__brands.json'),
  "Microwaves": require('../../data-scripts/resources/categories-brands/microwaves__brands.json'),
  "Kettles": require('../../data-scripts/resources/categories-brands/kettles__brands.json'),
  "Sandwich/Waffle Makers / Grills": require('../../data-scripts/resources/categories-brands/sandwich----waffle-makers---grills__brands.json'),
  "Irons": require('../../data-scripts/resources/categories-brands/irons__brands.json'),
  "Food Preparation": require('../../data-scripts/resources/categories-brands/food-preparation__brands.json'),
  "Juice Extractors/Citrus Presses": require('../../data-scripts/resources/categories-brands/juice-extractors-citrus-presses__brands.json'),
  "Vacuum Cleaners": require('../../data-scripts/resources/categories-brands/vacuum-cleaners__brands.json'),
  "Water Filters": require('../../data-scripts/resources/categories-brands/water-filters__brands.json'),
  "Electric Fans": require('../../data-scripts/resources/categories-brands/electric-fans__brands.json'),
  "Coffee Machines": require('../../data-scripts/resources/categories-brands/coffee-machines__brands.json'),
};